evilmartians/lefthook

cmd/run.go

Given the following example:
```yml
prepare-commit-msg:
scripts:
"jira_link.rb":
runner: ruby
```
Git args are not passed to the script.
This PR fixes this.

Proxy git args to scripts with custom runners

---

README.md

Add links to the post

---

cmd/root.go
cmd/run.go

1. Disable colored output if `--no-colors` flag specified
1. Force colored output if `colors: true` specified in the config.
1. Disable colored output if `colors: false` specified in the config.
1. Use old behavior by default: enable colors only for TTY
1. `IsTTY` replaced by `EnableColors`, because now it's about colors, not TTY.
Close #33 
Should I update some docs or do some tests? I haven't noticed a good place for it in the current codebase.
Thank you for the nice tool!

Flag to force or disable colored output

---

docs/full_guide.md
docs/other.md
docs/ruby.md

The same as #37. I used "question" word, not "questions" to be consistent with #37.

Fix typo in docs files

---

docs/other.md
docs/ruby.md

I followed the configuration/setup for Ruby, and have the following lefthook.yml config:
```
---
pre-commit:
commands:
brakeman:
run: bundle exec brakeman
```
I noticed that brakeman "gets stuck":
I tried a number of flags (parallel, output, debug, bundler, no bundler, etc.) but I think the cause is the default paging behavior which the brakeman docs note [here](https://brakemanscanner.org/docs/options/):
> By default, Brakeman pages output to the terminal with the less pager. To have Brakeman output directly to terminal, use `brakeman --no-pager`
I thought this might be a useful improvement to the docs in case anyone else runs into this
I'm running macOS Mojave, brakeman 4.6.1 (via gem install), lefthook 0.6.3 (via gem install), ruby 2.6.3

Add --no-pager flag to brakeman

---

README.md

Remove curly brackets since we only have `.rb` files here

Remove curly brackets

---

docs/ruby.md

`git diff --name-only HEAD master` doesn't show the _current_ files that
are staged for changes, only the previously committed changes
I think using `--staged` is a better example for the docs, because it will
run the command against the files you are committing. I think it better
represents what people expect to happen (the files I'm trying to commit will
have rubocop run against them)
I can throw an example git repo up w/ some examples of why I think this
is a better option to present as a default if that helps, but here's a screenshot:
- I'm on a branch (off of master)
- I had 1 commit where I added `test.rb` file to the branch
- I have `foo_spec.rb` staged, and I'm adding it as a commit to the branch
Using `HEAD master` I only see the `test.rb` file in the output; so lefthook actually …

Ruby example use staged for git diff

---

docs/full_guide.md

See #45.
https://docs.rubocop.org/en/latest/configuration/#includingexcluding-files

Add note about RuboCop configuration

---

CHANGELOG.md
cmd/root.go
docs/full_guide.md

add-extends-option

---

cmd/run.go

It's PR fix https://github.com/Arkweid/lefthook/issues/81
Problem: `Lefthook` launches runner passing the absolute path to the executable.
The container having the volume mounted from the host machine which provides source code has other paths to the executable files in absolute form.
Solution - use a relative path to executable files.
Perhaps a better solution would be to use a key in a config file that will be determined in what form the path should be transmitted.

Use relative path to script/executable file

---

.npm/postinstall.js

Attempt to resolve issue https://github.com/Arkweid/lefthook/issues/85

Fixed path to binaries in postinstall script

---

cmd/add.go

lefthook can't recognize git-worktree directory.
```
mkdir repo
cd repo
git init
lefthook install
git add lefthook.yml && git commit -m "Initial commit"
git worktree add -b worktree-test-branch ../repo2
cd ../repo2
touch test.txt && git add test.txt && git commit -m "Update" test.txt # error!
```
This PR gives git-worktree support to lefthook.

Add support for git-worktree

---

cmd/add.go

There are minor changes to support interactive pre-commit scripts.

Use eval instead of exec; Enable tty for the shell

---

cmd/add.go
cmd/root.go

removed sh from dependencies in root and add commands.
fixes #90
fixes #91

Fix execution on windows

---

cmd/install.go
cmd/root.go
cmd/uninstall.go
spec/fixtures/lefthook.yaml
spec/install_spec.rb
spec/support/file_structure.rb
spec/support/hook_examples.rb

Closes #101 
Added possibility to use files for a config with `yaml` extension.
Questions to discuss:
1. I haven't added tests, because locally they are failed even on the master, Do I need to perform something special?
2. In `cmd/install.go:189` you can see `primaryMatch`, this code will just take first match fr config file. Do we need anything special for it? (IMHO, no)

Add possibility for using multiple file types (#101)

---

cmd/add.go

Call 'lefthook' Go binary returns failed retval because of 'subcommand is required'
How to reproduce:
```
$ go get github.com/Arkweid/lefthook
$ lefthook >/dev/null 2>&1
$ echo $?                                    # returns '1'
$ lefthook -h >/dev/null 2>&1
$ echo $?                                    # returns '0'
```
Other methods (`bundle exec` & `npx`) are fine without `-h` actually

Fix: use '-h' for robust lefthook (Go binary) existence checking

---

.npm/README.md
README.md
docs/full_guide.md
examples/complete/lefthook-local.yml

Not a huge deal but `docker exec --rm` is not a valid command.

Update docker examples in guides

---

cmd/add.go

If user doesn't have `npx` but has `yarn` we should check it and call `yarn $cmd`
`npx $cmd` and `yarn $cmd` do pretty much the same: execute binary from `node_modules`.
Tested this solution on my machine (I don't have `npx` and prefer `yarn`). Works as intended.

Add yarn to template

---

cmd/cmd_test.go
cmd/root.go
docs/full_guide.md

Hello,
I would like to add the ability to use multiple extends. This was requested as a feature at my company as we are using Monorepo with many different projects (that are not separate git submodules), and using just one YML to manage all of those projects makes it become some GOD huge and unreadable file.
**With this PR in effect, you can define and use multiple extends like this:**
```
extends:
- landing/lefthook-landing.yml
- backend/lefthook-backend.yml
```
@Arkweid 🙏

Feature: Ability to use multiple extends

---

cmd/run.go
cmd/run_windows.go
docs/full_guide.md

**Type**: feature
**Scope**: commands
**Related issues**: fixes #133
Added functionality to propagate Git hook script invocation arguments to Lefthook commands in the form of positional shorthands such as `{1}` for the first argument, `{2}` for the second, etc.
Also introduced `{0}` as the equivalent shorthand of `{1} {2} ...` (space joint string of individual Git hook arguments) so all arguments can be passed down to command calls with one shorthand regardless of the actual argument count.
To improve script vs. command feature parity and make commands able to use Git hook arguments directly.
Some Git hooks pass down arguments to the hook scripts to specify what is happening exactly.
An example is `commit-msg` where the file containing the proposed commit message is passed down as a …

feat(commands): added Git hook argument handling

---

.npm/bin/index.js
.npm/bin/lefthook
cmd/add.go

Using lefthook through the NPM package causes performance issues, because NPX is a bit slow to start and execute each time lefthook is invoked. This can especially being seen when doing rebases with dozens of commits.
Here's a basic benchmark between native binary and NPM:
```shell
$ time lefthook version
0.7.2
lefthook version  0.01s user 0.01s system 85% cpu 0.014 total
$ time npx lefthook version
0.7.2
npx lefthook version  0.09s user 0.04s system 97% cpu 0.125 total
```
If you rebase some commits, it will take ~9 times longer to finish rebasing with NPM vs native binary.
This PR makes the hooks search for the final binaries by themselves, rather than using the `npx` command (which is now only used as a fallback).
Here's a benchmark comparing native binary, NPM before this PR, and NPM …

Improve performance with NPM package

---

.npm/bin/lefthook
cmd/add.go

This PR fixes bugs introduced in https://github.com/Arkweid/lefthook/pull/146#issuecomment-695076730. 
[The SH script used for NPM](https://github.com/Arkweid/lefthook/blob/58f641c74298adf7fb7fd7ae117875271aaa4c63/.npm/bin/lefthook) was written with poor knowledges of the differences between Bash and SH. I did some research and used https://www.shellcheck.net/ to help me rewrite properly the script and stay POSIX-compliant.
Please, tell me if you see any more issues.

Fix incompatible Bash features used in SH scripts

---

CHANGELOG.md
cmd/uninstall.go

[Sometimes](https://github.com/evilmartians/lefthook/issues/158) `.git/hooks` directory does not exist and lefthook fails to init hooks. The solution is to create the directory when it does not exist.
Closes #158.

Create .git/hooks directory when it does not exist

---

CHANGELOG.md
cmd/root.go

Improve check for installed git

---

cmd/cmd_test.go
cmd/uninstall.go

We don't need MkdirAll anymore since we check that `.git` directory exists

Remove MkdirAll from DeleteGitHooks

---

.npm/bin/lefthook

Hi!
Since version 0.7.3, the installation on Windows + [Git Bash](https://gitforwindows.org/) for NodeJS projects fails.
Git Bash uses the bash MSYS and the `lefthook` script doesn't support it, failure output example:
```
MSYS_NT-10.0-19043 x86_64
Unsupported OS: MSYS_NT-10.0-19043
```
This patch fixes this issue.
Thank you

fix: failing installation on Windows + MSYS

---

cmd/add.go
cmd/cmd_test.go
cmd/install.go
cmd/root.go
cmd/uninstall.go

Resolves #170
This PR adds `getGitHooksPath()` helper as a source of truth about where git hooks are stored
It uses `git rev-parse --git-path hooks` command under the hood (kudos to @stevelacy for the hint!), so it considers possible [overriding](https://git-scm.com/docs/githooks) default `.git/hooks` too 
This is my first PR to the repo, so please, let me know, if I can improve it in any way

`getGitHooksPath` helper function

---

cmd/run.go
docs/full_guide.md

Decided to tackle some further issues raised [here](https://github.com/evilmartians/lefthook/issues/78#issuecomment-658333189). There was mention of using a global environment variable so you didn't need to rely on the yaml having it configured. This is personal preference after all.
*My* personal preference is I like it very quiet. So I made it so you could get rid of the summary line as well.

Add ability to skip summary output. Also support a LEFT_QUIET env variable

---

cmd/templates/hook.tmpl
spec/fixtures/pre-commit
spec/fixtures/pre-push

Fixes https://github.com/evilmartians/lefthook/issues/192
The problem arises when:
1. using worktrees
2. lefthook is installed via NPM and isn't available in $PATH
3. lefthook version in main worktree's `package.json` is different from version in the current worktree
Then previously used code always return path to main worktree and founds old Lefthook binary there.
Current code will return path to the root of currently used worktree.
In most cases plain `pwd -P` would be enough but [docs for git hooks](https://git-scm.com/docs/githooks) states that:
> Before Git invokes a hook, it changes its working directory to either $GIT_DIR in a bare repository or the root of the working tree in a non-bare repository. An exception are hooks triggered during a push (pre-receive, update, post-receive, …

Fix path for searching npm-installed binary when in worktree

---

cmd/root.go
cmd/run.go
docs/full_guide.md

`skip` now allows to skip a certain hook during merge or rebase, configuration example:
```
pre-commit:
commands:
commit-colors:
run: commit-colors $(git rev-parse HEAD)
skip:
- merge
- rebase
```
Things to do:
Things to discuss:
- should we refactor run and run_windows to avoid duplicating the code?
- ~is there a better name than `skip_git_states`?~ using old `skip` option
- is there a better way to determine that merge or rebase are happening?
Closes #115

Allow skipping hooks in certain git states: merge and/or rebase

---

cmd/root.go

This PR resolves https://github.com/evilmartians/lefthook/issues/206 and https://github.com/evilmartians/lefthook/issues/90.
The root cause is that `git` commands were being run for all subcommands, instead of just the ones that needed them. This PR changes when the git config is resolved so that the problematic commands are not run for `version` and `help`.
Additionally, it slightly improves the error message when you invoke a subcommand that does need to be run from within a git repo. Previously, it would produce a cryptic `exit status 128` response.

do not init git config on help and version cmds

---

docs/node.md

It turns out that the lefthook package is actually a fake, and shouldn't be run, instead you'd want this change.

node: fix docs to actually refer to the correct package

---

cmd/templates/hook.tmpl

npx will automatically install the module if not present. yarn does not do this and complains when the package.json is not found.

Allows lefthook to work when node_modules is not in root folder for npx

---

cmd/templates/hook.tmpl
spec/fixtures/pre-commit
spec/fixtures/pre-push

Pass all arguments to downstream hooks

---

.rubygems/bin/lefthook

This PR replaces `File.exists?` with `exist?` in the Ruby wrapper.
`File.exists?` has been deprecated for many years. And it will be removed since the next release of Ruby (Ruby 3.2).
It displays a warning on Ruby 3.1 with `-w` option.
```bash
$ env RUBYOPT=-w lefthook install
/Users/kuwabara.masataka/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/lefthook-0.7.7/bin/lefthook:30: warning: File.exists? is deprecated; use File.exist? instead
Added config:  /path/to/lefthook.yml
```
It fails on Ruby 3.2-dev.
```bash
$ lefthook install
/Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.2.0+0/gems/lefthook-0.7.7/bin/lefthook:30:in `<top (required)>': undefined method `exists?' for File:Class (NoMethodError)
unless File.exists?(cmd)
^^^^^^^^
Did you mean?  exist?
from …
```

Replace deprecated `File.exists?` with `exist?` for Ruby script

---

cmd/templates/hook.tmpl

Issue: When installing lefthook via yarn (`yarn add --dev @arkweid/lefthook`) we get the following tree in node_modules:
```
@arkweid
└── lefthook
├── README.md
├── bin
│   ├── index.js
│   ├── lefthook_darwin_amd64
│   │   └── lefthook
│   ├── lefthook_darwin_arm64
│   │   └── lefthook
│   ├── lefthook_linux_386
│   │   └── lefthook
│   ├── lefthook_linux_amd64
│   │   └── lefthook
│   ├── lefthook_linux_arm64
│   │   └── lefthook
│   ├── lefthook_windows_386
│   │   └── lefthook.exe
│   └── lefthook_windows_amd64
│       └── lefthook.exe
├── get-exe.js
├── package.json
└── postinstall.js
```
However the hooks expect the path: `"$dir/node_modules/@arkweid/lefthook/bin/lefthook"`, falling back to npx when not available 😄 
This commit fixes the path.

fix(hook.tmpl): adds cpu arch and os arch to `lefthook`'s filepath

---

cmd/templates/hook.tmpl

Resolves https://github.com/evilmartians/lefthook/issues/241
For devs who are using yarn as their package manager, the git hook
templates are conditioned so that it will never attempt to run `yarn
lefthook` from the local package it is installed in. Instead, the
conditional will always end with `npx @arkweid/lefthook` which ends up
fetching the package via network.
In the worst case, the dev will fetch this package twice, once in the
`elif` conditional and again within the `then` block, causing a
significiant delay before the lefthook binary is executed. This degrades
performance to an almost unusable state.
To fix, give `yarn` a chance to find the lefthook binary within its
local cache before moving on to `npx`.

Fix unreachable conditional in hook template

---

docs/full_guide.md

- Relates to this issue: https://github.com/evilmartians/lefthook/issues/122 The solution provided here doesn't stop the process of committing.
- Also mentioned here https://github.com/evilmartians/lefthook/issues/110 but I find that is not the right solution as it doesn't use commitlint.

Add commitlint example in full_guide

---

.goreleaser.yml

This brings back the archived binaries. This makes downloading the binaries faster in #188. This also means that we can fulfill the needs of all parties (those who requested raw binaries in the release and us who are writing an automated code to download the binaries for the npm package).
To test this:
```
goreleaser --snapshot --skip-publish --rm-dist
```

Include archived binaries in the releases

---

internal/config/command.go

Closes #283
Check if the result of `Sub` isn't a null pointer.

Panic on commands structure misuse

---

internal/lefthook/run.go
internal/templates/hook.tmpl
internal/templates/templates.go

An alternative fix for https://github.com/evilmartians/lefthook/pull/280
This PR brings old behavior back + adds silent processing for `prepare-commit-msg` hook.

Bring auto install back

---

CHANGELOG.md
internal/config/skip.go
internal/git/repository.go
internal/git/state.go
internal/lefthook/add_test.go
internal/lefthook/install_test.go
internal/lefthook/lefthook.go
internal/lefthook/run_test.go
internal/lefthook/runner/runner.go
internal/lefthook/uninstall_test.go

Closes: #279
- Fix comparing git state and skip options (missed typecast)
- Add a test for this feature
- Pass `fs` to `git.Repository` to support testing and use dependency injection

Support skipping on rebase

---

packaging/rubygems/bin/lefthook

Making this change locally allowed me to run lefthook. I do not *know* if there are any kind of ABI issues, I have no *actual* idea how lefthook works, but I suspect it's fine since it looks like there's no actual interface between go and ruby, only at the process level?
Fixes https://github.com/evilmartians/lefthook/issues/296

Add `when "mingw" then "windows"` case

---

Makefile
cmd/version.go
internal/config/available_hooks.go
internal/git/repository.go
internal/lefthook/add.go
internal/lefthook/install.go
internal/lefthook/install_test.go
internal/lefthook/lefthook.go
internal/lefthook/run.go
internal/templates/templates.go
internal/version/version.go

Relates to https://github.com/evilmartians/lefthook/issues/279
- Store lefthook config checksum not in `prepare-commit-msg`, but in `lefthook.checksum` file.
- Make sure config is synchronized when calling `run` command.

Store lefthook checksum in non-hook file

---

internal/config/command.go
internal/config/script.go
internal/lefthook/run.go
internal/lefthook/runner/result.go
internal/lefthook/runner/runner.go

Closes https://github.com/evilmartians/lefthook/issues/266
```yaml
check:
commands:
cmd:
run: exit 1
fail_text: "Try 'exit 0' instead of 'exit 1'"
```
```
> $ lefthook run check
Lefthook v1.0.4
RUNNING HOOK: check
EXECUTE > cmd
SUMMARY: (done in 0.00 seconds)
🥊  cmd: Try 'exit 0' instead of 'exit 1'
```

Add fail text

---

.github/workflows/lint.yml
.goreleaser.yml
Makefile
internal/config/script.go
internal/lefthook/runner/execute_unix.go
internal/lefthook/runner/execute_windows.go
internal/lefthook/runner/executor.go
internal/lefthook/runner/runner.go
internal/lefthook/runner/runner_test.go

**Summary :broom:**
Things to be done:
- Test files filtering
- Test skipping if filters are empty
- Test args coming to Executor

Add tests on runner

---

.github/workflows/test.yml
.goreleaser.yml
CONTRIBUTING.md
go.mod
internal/lefthook/runner/runner_test.go

Bump go version

---

docs/full_guide.md
internal/git/lfs.go
internal/lefthook/run.go
internal/lefthook/runner/execute_unix.go
internal/lefthook/runner/execute_windows.go
internal/lefthook/runner/executor.go
internal/lefthook/runner/runner.go
internal/lefthook/runner/runner_test.go

Closes https://github.com/evilmartians/lefthook/issues/276
The approach is [taken from Githooks](https://github.com/gabyx/Githooks/blob/8025718df966574e12485ecdb8bbe5b6ffd050f1/githooks/apps/runner/runner.go#L379-L409):
Tested locally, noticed that `git lfs ...` hangs only if I set `cmd.Stdin = os.Stdin`. This is because `pre-push` hook reads from STDIN: https://www.mankier.com/1/git-lfs-pre-push. :warning: Lefthook won't support this for now.

Add support for git lfs

---

packaging/npm/lefthook-darwin-arm64/install.js
packaging/npm/lefthook-darwin-arm64/package.json
packaging/npm/lefthook-darwin-x64/install.js
packaging/npm/lefthook-darwin-x64/package.json
packaging/npm/lefthook-linux-arm64/install.js
packaging/npm/lefthook-linux-arm64/package.json
packaging/npm/lefthook-linux-x64/install.js
packaging/npm/lefthook-linux-x64/package.json
packaging/npm/lefthook-windows-arm64/install.js
packaging/npm/lefthook-windows-arm64/package.json
packaging/npm/lefthook-windows-x64/install.js
packaging/npm/lefthook-windows-x64/package.json

Closes https://github.com/evilmartians/lefthook/issues/294

Add install command to npm package

---

internal/templates/hook.tmpl

Closes https://github.com/evilmartians/lefthook/issues/298
**Summary :wrench:**
If we have `.Extension` we must be on Windows. Check for lefthook.bat executable too.

Check for lefthook.bat in hook template

---

docs/full_guide.md
internal/lefthook/runner/execute_windows.go
internal/lefthook/runner/runner.go
internal/lefthook/runner/runner_test.go

Closes https://github.com/evilmartians/lefthook/issues/269
**Summary :wrench:**
This bug is from go `exec` builtin package: https://cs.opensource.google/go/go/+/refs/tags/go1.19:src/os/exec/exec.go;l=269. They suggest passing args directly with syscall attrs. This is what is done with this PR.
Also fixed a thing: if the {staged_files} or any other template is quoted like "{staged_files}", all the files from substitution will be quoted. Previously the whole line was quoted, and this is not what you want on Windows, I think.

Windows escaping issues

---

internal/lefthook/runner/runner.go

Relates to https://github.com/evilmartians/lefthook/pull/314, fixes https://github.com/evilmartians/lefthook/pull/314#issuecomment-1221405004
**Summary :wrench:**
When executing scripts, quote the path to it. The path may contain characters that need quoting (e.g. spaces).

Quote path to script

---

internal/lefthook/runner/runner.go

#314 introduced a [regression](https://github.com/evilmartians/lefthook/pull/314#issuecomment-1230927802) that passes quoted paths to `fs.chmod`. [`fs.Chmod`/`os.chmod` on windows](https://cs.opensource.google/go/go/+/master:src/syscall/syscall_windows.go;l=647;drc=242adb784cd64265ce803f6b0c59dbf126bcda9c) calls into the [`GetFileAttributes`](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfileattributesw)/[`SetFileAttributes`](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setfileattributesw) win32 api directly. The win32 api expects a "strongly typed" path, without quotes, unlike a command line string, and doesn't try to *parse* it. Passing quoted paths to fs.Chmod causes the operation to fail - valid paths do not begin with quotes!
This …

Fix regression from #314 (chmod missed fix)

---

docs/full_guide.md
internal/lefthook/runner/runner.go
internal/lefthook/runner/runner_test.go

Closes https://github.com/evilmartians/lefthook/issues/317

Exclude by command names too

---

internal/lefthook/runner/runner.go
internal/log/log.go

Closes https://github.com/evilmartians/lefthook/pull/336
Print the current running commands/scripts:
```yaml
test:
parallel: true
commands:
command1:
run: sleep 1
command2:
run: sleep 3
command3:
run: sleep 4
```
```bash
$ lefthook run test
Lefthook v1.1.2
RUNNING HOOK: test
EXECUTE > command1
⠧ waiting: command3, command2
```

Show current running commands and scripts

---

docs/full_guide.md
internal/config/command.go
internal/config/script.go
internal/lefthook/runner/execute_unix.go
internal/lefthook/runner/execute_windows.go
internal/lefthook/runner/executor.go
internal/lefthook/runner/runner.go
internal/lefthook/runner/runner_test.go

Closes https://github.com/evilmartians/lefthook/issues/247
There might be a need to pass an ENV variables to a command or a script. To make this thing simple and working on any OS I suggest an option `env` that can be applied to a command or script.

Allow setting env vars

---

docs/configuration.md
examples/remote/ping.yml
go.mod
go.sum
internal/config/config.go
internal/config/load.go
internal/config/load_test.go
internal/config/remote.go
internal/git/remote.go
internal/lefthook/add.go
internal/lefthook/add_test.go
internal/lefthook/install.go
internal/lefthook/install_test.go
internal/lefthook/run.go
internal/lefthook/runner/runner.go
internal/lefthook/runner/runner_test.go
internal/lefthook/uninstall_test.go

Closes https://github.com/evilmartians/lefthook/issues/155, https://github.com/evilmartians/lefthook/pull/323
Remotes allow to share lefthook configurations without a need to maintain one `lefthook.yml` in all repos where you need it to be unique.
For example:
```yaml
remotes:
git_url: git@github.com:evilmartians/lefthook # Repo URL (https:// or git@)
ref: v1.2.0                                   # Optional reference (tag or branch)
config: examples/ruby-linters.yml             # Optional file path (default is lefthook.yml)
```
**:tomato: This PR tasks**

feature: Add remote config support

---

docs/configuration.md
internal/lefthook/runner/execute_unix.go
internal/lefthook/runner/execute_windows.go
internal/lefthook/runner/runner.go
internal/lefthook/runner/runner_test.go

Closes https://github.com/evilmartians/lefthook/issues/125

Full support for interactive commands and scripts

---

CHANGELOG.md
docs/configuration.md
internal/git/remote.go

Closes https://github.com/evilmartians/lefthook/discussions/358
:warning: There is still a problem when you had a `ref`, then removed it and ran `lefthook install`. The reason for that is - we don't know which branch to use as a default. So, the suggestion is: decide whether you use ref or not, and if you added a `ref`, please keep it there.

fix: Allow changing refs for remote

---

internal/lefthook/uninstall.go
internal/lefthook/uninstall_test.go

This fix ensures that the `lefthook uninstall` command removes the `.git/info/lefthook.checksum` file.
It closes #366.

fix: remove lefthook.checksum on uninstall

---

CHANGELOG.md
internal/lefthook/runner/runner.go

Closes https://github.com/evilmartians/lefthook/issues/367, https://github.com/evilmartians/lefthook/pull/369
Thanks to @stonesbg who found a regression. No need to quote the scripts path. This leads to a bug on Windows system.

fix: Remove quoting for scripts

---

CHANGELOG.md
docs/usage.md
internal/lefthook/runner/execute_unix.go
internal/lefthook/runner/execute_windows.go
internal/lefthook/runner/executor.go
internal/lefthook/runner/runner.go
internal/lefthook/runner/runner_test.go

Closes https://github.com/evilmartians/lefthook/issues/356

fix: Omit lfs output unless it is required

---

CHANGELOG.md
docs/configuration.md
internal/config/hook.go
internal/config/load_test.go
internal/config/skip.go
internal/git/state.go
internal/lefthook/runner/runner.go
internal/lefthook/runner/runner_test.go

Closes https://github.com/evilmartians/lefthook/issues/354

feature: Skip based on branch name and allow global skip rules

---

README.md
docs/configuration.md

Closes https://github.com/evilmartians/lefthook/issues/380
Fixed forgotten links referencing old documentation.

docs: Update links

---

.github/dependabot.yml

- Add dependabot auto updates for Go modules every Monday at 6:00 UTC

chore: Add dependabot

---

CHANGELOG.md
docs/configuration.md
internal/config/config.go
internal/lefthook/add.go
internal/lefthook/install.go
internal/lefthook/lefthook.go
internal/templates/hook.tmpl
internal/templates/templates.go

Closes https://github.com/evilmartians/lefthook/pull/185 https://github.com/evilmartians/lefthook/issues/178 https://github.com/evilmartians/lefthook/issues/99 https://github.com/evilmartians/lefthook/issues/253 https://github.com/evilmartians/lefthook/issues/249

feature: Allow providing rc file

---

.github/workflows/lint.yml
.golangci.yml
Makefile
cmd/run.go
docs/configuration.md
internal/config/config.go
internal/config/load.go
internal/lefthook/run.go
internal/lefthook/run_test.go
internal/lefthook/runner/runner.go

Closes https://github.com/evilmartians/lefthook/issues/208

feature: Add an option to disable spinner

---

internal/templates/hook.tmpl

Closes #403 
Added double-quotes to `eval` statements that use $dir

fix: Double quote eval statements with $dir

---

internal/git/repository.go

Closes #413
The presence of `.git/info` directory has been taken for granted, but it can be actually nonexistent. This results in an unhandled enoent. I've changed it so the presence of it is made sure when initializing Repository. 
The point I believe is that `.git/info` could be absent. On the other hand I'm not sure if we can take for granted that `.git/hooks` always exists, or the same mishap can occur. At least in my environment the hooks dir is provisioned automatically (where the info is not) but I haven't been able to reason about it documentationally.
This does fix my problems but since I'm not really sure what the scope of fix should be, any feedback is welcome. Thanks in advance!

fix: Make info dir when it is absent

---

CHANGELOG.md
internal/git/repository.go

Closes https://github.com/evilmartians/lefthook/issues/417
When repo is added as a worktree, its info path is absolute, but when not, it is relative. So, just `Clean`-ing the path to make sure it is correctly interpreted.

fix: Don't join info path with root

---

go.mod
go.sum

Closes #425
update github.com/briandowns/spinner to [v1.21.0](https://github.com/briandowns/spinner/releases/tag/v1.21.0) fixed the leak

fix: memory leak dependency

---

internal/git/exec.go
internal/git/repository.go

Closes https://github.com/evilmartians/lefthook/issues/374
- Try using @{push}
- If it doesn't work - find out the branch name looking at remote's HEAD and use it

fix: Use correct branch for {push_files} template

---

internal/lefthook/add.go
internal/lefthook/install.go

Closes https://github.com/evilmartians/lefthook/issues/430

fix: Force creation of git hooks folder

---

internal/git/exec.go

Closes https://github.com/evilmartians/lefthook/issues/433

fix: Allow sh syntax in files

---

.goreleaser.yml

fix: restore release assets name

---

internal/config/load.go

fix: don't extra extend config if lefthook-local.yml is missing

---

CHANGELOG.md
docs/configuration.md
internal/config/available_hooks.go
internal/lefthook/run_test.go
internal/lefthook/runner/prepare_command.go
internal/lefthook/runner/runner.go
internal/lefthook/runner/runner_test.go

Closes https://github.com/evilmartians/lefthook/issues/446 https://github.com/evilmartians/lefthook/issues/441 https://github.com/evilmartians/lefthook/issues/228

feat: implitic skip on missing files for pre-commit and pre-push hooks

---

CHANGELOG.md
internal/lefthook/runner/prepare_command.go
internal/lefthook/runner/runner.go
internal/lefthook/runner/runner_test.go

Closes https://github.com/evilmartians/lefthook/issues/447

fix: stage fixed when root specified

---

.github/dependabot.yml
CHANGELOG.md
internal/config/load.go
internal/lefthook/run.go

Relates to https://github.com/evilmartians/lefthook/issues/212
When there's no lefthook.yml we should't fail. No config == empty config (but still with a warning).

fix: don't fail on missing config file

---

CHANGELOG.md
docs/configuration.md
internal/config/skip.go
internal/config/skip_test.go

Closes https://github.com/evilmartians/lefthook/issues/456

feat: allow globs in skip option

---

internal/templates/hook.tmpl

On Linux Ubuntu 22.04, `/bin/sh` doesn't support `source` command, so if you run this template you get an error like the following one:
```
> git commit -m wip
.git/hooks/pre-commit: 8: source: not found
```
Replacing `source` with `.` fixed it. Also, [`dot` seems to be the POSIX standard](https://stackoverflow.com/q/11588583).

fix: make hook template compatible with shells without source command

---

internal/lefthook/runner/prepare_command.go

It address the use case outlined here
https://github.com/evilmartians/lefthook/issues/315#issuecomment-1491670663
```yaml
post-checkout:
commands:
01-bundle-install:
files: git diff --name-only {1} {2}
glob: '*Gemfile'
run: bundle install
```
I wasn't able to test it because the line I changed is not covered by current tests

feat: pass numeric placeholders to files command

---

internal/config/load.go
internal/config/load_test.go

Without this patch is not possible to define extra hooks in local config, e.g.
```yaml
tests:
commands:
tests:
run: go test ./...
```
and 
```yml
lints:
scripts:
"linter.sh":
runner: bash
```
Won't work, it wont be possible to run `lefthook run lints`
Iterate against both global and local top level keys when adding custom hooks.

feat: allow extra hooks in local config

---

docs/configuration.md
internal/lefthook/runner/runner.go
internal/log/skip_settings.go

Closes https://github.com/evilmartians/lefthook/discussions/467
If you have lots of commands, and make small commits, you'll often see a lot of skipped commands:
```
sorbet: (SKIP. NO FILES FOR INSPECTION)
stylelint: (SKIP. NO FILES FOR INSPECTION)
codeowners: (SKIP. NO FILES FOR INSPECTION)
authorization: (SKIP. NO FILES FOR INSPECTION)
svgo: (SKIP. NO FILES FOR INSPECTION)
syncpack: (SKIP. NO FILES FOR INSPECTION)
eslint: (SKIP. NO FILES FOR INSPECTION)
packwerk: (SKIP. NO FILES FOR INSPECTION)
rubocop: (SKIP. NO FILES FOR INSPECTION)
```
I wanted a way to skip this. I'm migrating from a home grown hook runner, and it had pretty concise output that I'm trying to recreate. I was able to do that with most of the other options, but still had this output.
I apologize in advance, this is my …

feat: don't show when commands are skipped because of no matched files

---

internal/config/load.go
internal/lefthook/run.go

Add a debug log when hook is being skipped because it doesn't exist in a config file.

chore: debugs

---

docs/configuration.md
internal/lefthook/run.go
internal/lefthook/runner/runner.go
internal/log/skip_settings.go
internal/log/skip_settings_test.go

Closes https://github.com/evilmartians/lefthook/issues/473
Adds `execution_out` to `skip_output` setting (or LEFTHOOK_QUIET)

feat: add execution_out to skip output settings

---

internal/lefthook/runner/runner.go

Closes https://github.com/evilmartians/lefthook/issues/473
Make sure that command names are displayed when skipping `execution_out` with `follow`/`interactive` mode

fix: allow skipping execution_out with interactive mode

---

docs/configuration.md
internal/config/command.go
internal/config/hook.go
internal/config/load_test.go
internal/config/script.go
internal/config/skip.go
internal/config/skip_test.go
internal/lefthook/runner/prepare_command.go
internal/lefthook/runner/prepare_script.go
internal/lefthook/runner/runner.go
internal/lefthook/runner/runner_test.go

Closes https://github.com/evilmartians/lefthook/issues/477
Add `only` option to hook, command, and script which acts as the opposite of `skip` option.

feat: add only option

---

cmd/dump.go
cmd/root.go
internal/config/command.go
internal/config/config.go
internal/config/hook.go
internal/config/script.go
internal/lefthook/dump.go

Sometimes it is useful to see how the config looks like after merging all extensions, `lefthook-local.yml`, and remotes. This PR adds `lefthook dump` command that prints config in YAML.
Further improvements: add `json` format.

feat: add dump command

---

internal/lefthook/runner/execute_unix.go
internal/lefthook/runner/runner.go

When using `interactive` the commands and scripts actually output to STDOUT even if `execution_out` is passed to `skip_oputput` options. This PR fixes it.

Skip output for interactive commands

---

testdata/add.txt
testdata/run_json.txt
testdata/run_toml.txt
testdata/run_yml.txt
testdata/uninstall.txt

chore: add more integrity tests

---

Makefile
internal/lefthook/runner/prepare_command.go
internal/lefthook/runner/runner.go
testdata/stage_fixed.txt
testdata/stage_fixed_505.txt

Closes https://github.com/evilmartians/lefthook/issues/505
Don't escape filenames when adding via `git add` (stage_fixed feature)

Auto stage non-standard files

---

internal/templates/hook.tmpl

Related to #510
This improves `hook.tmpl` by removing extra work and fixing subtle bugs in passing arguments with whitespace.
- The first commit removes a useless echo (more info can be found [here](https://www.shellcheck.net/wiki/SC2116))
- The second commit removes all "eval" builtins as they are not necessary. `$@` has been quoted in all places as should be to properly preserve whitespace.
- The third commit partially solves #510. I think it is OK to assume that `@evilmartians/lefthook` will be executed if `npx` exists. Cases where it may not may include when a directory has incorrect permissions or the registry cannot be resolved - cases in which the user has a broken configuration already. It is more frustrating when it is artificially slow, especially since `npx` kind of slow by …

Improve hook template

---

docs/configuration.md
examples/verbose/lefthook.yml

While I was creating a schema for lefthook [at SchemaStore](https://github.com/SchemaStore/schemastore/pull/3066), it seemed that there were some typos that could be fixed.
This fixes those (missed indentation and improved enumeration of allowed values in a config key).

Improve documentation and examples

---

internal/lefthook/lefthook.go
internal/lefthook/run.go

Previously, setting `LEFTHOOK_VERBOSE` would have no effect since cobra defaulted `options.Verbose` to false. And because `options.Verbose` wasn't overridden from the start, it would remain `false`.

fix: `LEFTHOOK_VERBOSE` properly overrides `--verbose` flag

---

internal/lefthook/uninstall.go
testdata/uninstall.txt

Uninstall `lefthook.toml` and `lefthook.json` if they exist.

fix: uninstall all possible formats

---

internal/lefthook/runner/runner.go

Closes #494
Prevents printing blank lines when `exececutionInfo` is not printed.
Previously, two newlines would be printed for each command (Effectively `fmt.Println("\n")`). This fixes that.

fix: Do not print extraneous newlines when executionInfo output is hidden

---

internal/config/load_test.go

While working on #521, I noticed that there were slight inconsistencies with filenames and cleanup logic in this test file. This PR fixes those subtle inconsistencies that could pose issue down the line.

test: Improve correctness of `load_test.go`

---

.github/workflows/release.yml
README.md
docs/install.md

Closes #136
[This action](https://github.com/vedantmgoyal2009/winget-releaser) automatically generates manifests for Winget Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.
Lefthook is now available in Winget: https://github.com/microsoft/winget-pkgs/pull/112810. This action would be used to update it.
**Before merging this:**
1. Add a **classic** PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN`.
2. Fork https://github.com/microsoft/winget-pkgs under @evilmartians. The action will use that fork for making a branch and creating a PR with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every release.
3. Install [Pull](https://github.com/apps/pull) on the winget-pkgs fork to …

ci: add Winget Releaser action

---

internal/config/load.go

Closes https://github.com/evilmartians/lefthook/issues/528
After merging extends from remote -- clear the `extends` value.

fix: correct merging of extends from remote config

---

docs/install.md

Related to #136
Add Scoop installation method. Lefthook was recently added to the Main bucket: https://github.com/ScoopInstaller/Main/pull/4967

docs: add scoop installation method

---

docs/configuration.md
internal/lefthook/run.go
internal/log/skip_settings.go
internal/log/skip_settings_test.go

Closes https://github.com/evilmartians/lefthook/issues/530
Add `empty_summary` to values of `skip_output` for those cases when there's commands to run for a hook (ie all have been skipped, or there's no files matching command patterns)

Add support for skipping empty summaries

---

.github/workflows/test.yml
CONTRIBUTING.md
README.md
go.mod

Closes: N/A
Upgrade go to 1.21, to support using the new `slices.Contains` in #534

chore: bump go to 1.21

---

cmd/run.go
docs/usage.md
internal/lefthook/run.go
internal/lefthook/runner/prepare_command.go
internal/lefthook/runner/runner.go

Closes #120
Adds `--all-files`, `--files`, and `--commands` to run lefthook on a subset of hooks and/or files in the repo.
New usage text:
```sh
$ lefthook run --help
Execute group of hooks
Usage:
lefthook run hook-name [git args...] [flags]
Examples:
lefthook run pre-commit
Flags:
--all-files          run hooks on all files
--commands strings   run only specified commands
--files strings      run on specified files. takes precedence over --all-files
-h, --help               help for run
-n, --no-tty             run hook non-interactively, disable spinner
Global Flags:
--no-colors   disable colored output
-v, --verbose     verbose output
```
I'm not sure how to add a test for these - there aren't any existing tests that operate on the `cmd/run.go` level and test the whole flow – how would …

feat: add `files`, `all-files` and `commands` as flags

---

.github/workflows/lint.yml
.github/workflows/release.yml
.golangci.yml
Makefile
cmd/version.go
internal/config/load.go
internal/config/script.go
internal/git/remote.go
internal/lefthook/lefthook.go
internal/lefthook/run_test.go
internal/lefthook/runner/runner.go
internal/lefthook/runner/runner_test.go
internal/lefthook/uninstall.go

- Update golangci-lint version 
- Remove odd revive rule
- Remove depguard (no need for it right now)
- Update golang version in CI workflows

chore: fix linter issues

---

internal/lefthook/run.go
internal/lefthook/run_test.go
testdata/run_non_existing.txt

Closes https://github.com/evilmartians/lefthook/issues/405
Return an error on non-existing hook if it is not a git hook

fix: fail on non existing hook name

---

internal/lefthook/run/exec/execute_unix.go
internal/lefthook/run/exec/execute_windows.go
internal/lefthook/run/exec/executor.go
internal/lefthook/run/prepare_command.go
internal/lefthook/run/prepare_command_test.go
internal/lefthook/run/prepare_script.go
internal/lefthook/run/runner.go
internal/lefthook/run/runner_test.go

Use simpler data structures - pass a `[]string` instead of `[][]string` as commands

chore: refactor commands passing

---

docs/configuration.md
docs/usage.md
internal/config/command.go
internal/config/script.go
internal/lefthook/run/exec/execute_unix.go
internal/lefthook/run/exec/execute_windows.go
internal/lefthook/run/exec/executor.go
internal/lefthook/run/runner.go

Closes https://github.com/evilmartians/lefthook/issues/508
`interactive` options is supposed to be used with interactive CLI commands. With `interactive: true` lefthook opens a TTY (for Linux/Unix), and scripts that use `while read ...` hang forever. This PR adds `use_stdin` option that doesn't touch a TTY device but forwards the stdin.

fix: add use_stdin option for just reading from stdin

---

README.md
docs/configuration.md
docs/usage.md

Closes https://github.com/evilmartians/lefthook/issues/496
Update the docs, remove odd words, make the sentences more useful.

docs: update readme with tldr instructions

---

internal/lefthook/run.go
internal/lefthook/run/exec/execute_unix.go
internal/lefthook/run/exec/execute_windows.go
internal/lefthook/run/exec/executor.go
internal/lefthook/run/runner.go
internal/lefthook/run/runner_test.go
testdata/run_interrupt.txt

Closes #542
Hitting Ctrl-C during commit would terminate `lefthook` immediately, and stashed changes would not be restored. This can be improved by using a `NotifyContext` which prevents `lefthook` from being killed while still terminating subprocesses.
1. In this repo…
2. Added to `.lefthook.toml`
```
[pre-commit.commands.sleep]
run = "sleep 10 && exit 1"
```
3. Staged that change
4. Added `# unstaged` at the end of `.lefthook.toml`
5. Ran `git commit -m 'test'`
6. Hit `Ctrl-C`
7. Ran `git status` && `git stash list`
8. Before:
- Output: `⠏ waiting: sleep^C`
- The `unstaged` comment was missing
- Found `stash@{0}: lefthook auto backup`
9. After:
- Output:
```
⠦ waiting: sleep^C
EXECUTE > sleep
Error: Interrupted
```
- The `unstaged` comment was restored
- Stash list was empty

feat: add interrupt (Ctrl-C) handling

---

Makefile
docs/install.md
internal/templates/hook.tmpl

Closes https://github.com/evilmartians/lefthook/issues/544
Updated the `hooks.tmpl` file to support executing lefthook from a Swift Plugin. Additionally, added a note into `docs/installation.md` with a link to the plugin repository.

feat: Initial support for Swift Plugins

---

docs/configuration.md
internal/templates/hook.tmpl

Doesn't close any issue.
There's currently a discrepancy with the documentation on [rc](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#rc) files and the actual behavior.
The documentation states:
> Provide a tweak to access npm executable the same way you do it in your ~/rc
However, `set -a` is not set by default (or at all in most people's configurations) in `~/.profile`, `~/.bashrc`, etc. If that were the case, then way too many environment variables would be added to the environment table of all child processes.
The correct behavior is already hinted at with the examples:
```sh
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
```
The `export` syntax is used, which implies that `set -a` is not enabled. Furthermore, when sourcing …

fix: Do not enable export when sourcing rc file

---

internal/lefthook/run/runner.go

Closes https://github.com/evilmartians/lefthook/issues/540
Fix sorting – from alphabetical to custom alphanumeric, respecting the preceding numbers

fix: correctly sort alphanumeric commands

---

internal/lefthook/lefthook.go
internal/lefthook/run.go

Closes https://github.com/evilmartians/lefthook/issues/560
Don't print separator for the summary section if nothing is printed before

chore: skip summary separator if nothing is printed

---

cmd/install.go
cmd/root.go
internal/lefthook/install.go
internal/lefthook/install_test.go
internal/lefthook/lefthook.go
internal/lefthook/run.go

Closes https://github.com/evilmartians/lefthook/issues/571

fix: don't check checksum file when explicitly calling lefthook install

---

cmd/add-doc.txt
cmd/add.go
docs/configuration.md
internal/git/exec.go
internal/lefthook/run.go

Fixed some spelling and grammar errors.

docs: spelling and grammar fixes

---

README.md
docs/configuration.md
examples/complete/lefthook.yml
internal/lefthook/run/filter/filters_test.go
internal/templates/config.tmpl

docs: glob and regexp related improvements

---

internal/git/repository.go

Closes https://github.com/evilmartians/lefthook/issues/584
Compatibility is much more important here. Probably need another fix for empty diffs

fix: drop new argument for git diff compatibility

---

CHANGELOG.md
internal/lefthook/run/exec/execute_unix.go
internal/lefthook/run/exec/execute_windows.go
internal/lefthook/run/exec/nullReader.go

Closes https://github.com/evilmartians/lefthook/issues/588
Right now commands that don't use STDIN still receive it, and lefthook copies STDIN from the TTY to those commands. This is not correct. This PRs enables STDIN forwarding only when an option is specified (`interactive` or `use_stdin`)

fix: use empty stdin by default

---

internal/config/config.go
internal/lefthook/run.go
internal/log/skip_settings.go
internal/log/skip_settings_test.go

Closes https://github.com/evilmartians/lefthook/issues/78
`skip_output: true` option that silences everything (except errors)

Added bool option for skip noise

---

internal/templates/hook.tmpl

`@evilmartians/lefthook` embeds all binaries and it is not optimal to download such a big package when only one binary is used. 
Change `@evilmartians/lefthook` to `lefthook` npm package for `npx` call.

fix: use lefthook package with npx

---

cmd/add.go
cmd/dump.go
cmd/install.go
cmd/run.go
cmd/uninstall.go
cmd/version.go
internal/lefthook/run.go
internal/lefthook/run_test.go

Improve shell completion by avoiding incorrect filename completions, and completing hooks for add and run.

feat: shell completion improvements

---

README.md

Closes https://github.com/evilmartians/lefthook/issues/605
Hide Wiki links since Wiki stuff is outdated.

chore: hide wiki links

---

cmd/run.go
docs/usage.md
internal/config/command.go
internal/config/files.go
internal/lefthook/run.go
internal/lefthook/run/prepare_command.go
internal/lefthook/run/runner.go
testdata/files_override.txt

Closes #564.
Lefthook is currently not completely ready for repositories with filenames that contain commas.
1. Add `--file` as the successor of `--files`. This option can be repeated for a list of file paths. `--files` is dangerous, e.g., one can create a file `README.md,..` and if it gets supplied to a fixer, who knows what happens.
2. Add `--files-from-stdin`. This option reads file paths from stdin, separated by a null character. This allows for file names with a comma or newline, and is interoperable with Git and Unix tools (e.g., `git ls-files -z`, `git diff --name-only -z`, `find -print0`).
@mrexox Can you test and add automated tests? I specifically advise to test interaction with existing stdin-related features.

More robust collection of file paths

---

cmd/run.go
internal/lefthook/run.go
testdata/files_override.txt

Closes https://github.com/evilmartians/lefthook/issues/564
Keep only null separation logic

fix: files from stdin only null separated

---

internal/log/skip_settings.go
internal/log/skip_settings_test.go

Closes #623 
Handles situations when only `LEFTHOOK_QUIET` exists, without `skip_output` in the `lefthook.yml` file

fix: handle LEFTHOOK_QUIET when there is no skip_output in config

---

internal/lefthook/run/exec/execute_unix.go

Closes  https://github.com/evilmartians/lefthook/issues/588
If I'm reading the code, this `args.in` should be a nullReader when non-interactive and not using stdin. For some reason though, it ends up capturing stdin. That is, any typing you do while lefthook is running goes to lefthook, instead of the shell invoking it.

Fix lefthook capturing stdin from terminal even if when non-interactive and not using stdin

---

internal/lefthook/add.go
internal/lefthook/install.go
internal/lefthook/lefthook.go
internal/templates/hook.tmpl
internal/templates/templates.go

Closes https://github.com/evilmartians/lefthook/issues/610 https://github.com/evilmartians/lefthook/issues/510

fix: respect roots in commands for npm packages

---

.github/ISSUE_TEMPLATE/config.yml

Updates `.github/ISSUE_TEMPLATE/config.yml` request help url to match this repo discussions

docs: update request help url

---

internal/log/log.go

Closes https://github.com/evilmartians/lefthook/issues/566
Adaptive colors do a special sequence to the TTY that `pty` can't handle (in case lefthook is being called from one of the commands). Also it can take upto 3 seconds for this logic (https://github.com/charmbracelet/lipgloss/issues/73). In this PR I drop special colors for the light setup. 
If you have a light theme and feel weird, please submit a PR or an issue with the change.

chore: remove adaptive colors

---

internal/lefthook/run/prepare_command.go

Closes https://github.com/evilmartians/lefthook/issues/655
There were issues with 8000 limit. I assume that decreasing the limit to 7k will fix the issue.

fix: decrease max cmd length for windows

---

docs/usage.md
internal/templates/hook.tmpl

This adds `LEFTHOOK_PATH` to the `.git/hook` templates. It's used first before 
This is something that would have been helpful while working on https://github.com/evilmartians/lefthook/issues/588 and I was testing against a locally built 
While I was here, I added `set -x` when `LEFTHOOK_VERBOSE` is on. This is another thing that would have been useful, and I also used it to help validate LEFTHOOK_PATH working 😁  Let me know if I should split it out separately.

Configurable path to lefthook to run during git hook

---

internal/templates/hook.tmpl

Closes https://github.com/evilmartians/lefthook/issues/667
Change the order of the packages to run lefthook – use swift package before npx

fix: use swift package before npx

---

docs/configuration.md
internal/config/config.go
internal/lefthook/run.go
internal/lefthook/run/runner.go
internal/lefthook/run/runner_test.go
internal/log/log.go
internal/log/settings.go
internal/log/settings_test.go
internal/log/skip_settings.go
internal/log/skip_settings_test.go

Closes #592 
Deprecate the `skip_output` and add `output` as a whitelist of output values
I saved the `skip_output` logic for further removal in the next versions

Add new output instead skip_output

---

internal/lefthook/run.go
internal/lefthook/run/runner.go
internal/lefthook/run/runner_test.go
internal/log/settings.go
internal/log/settings_test.go

The mechanism for *allow* settings differs from *skip* approach. This PR fixes this for summary and output logs

fix: fix printing when using `output` log setting

---

internal/lefthook/run.go
internal/log/skip_settings.go
internal/log/skip_settings_test.go

Fix skip_settings related to summary, success and failure logging. Skipping summary skips failure and success.

chore: skip printing deprecation warning

---

docs/configuration.md

Closes https://github.com/evilmartians/lefthook/issues/569
To keep things simple let's allow only comma-separated list of tags

docs: allow only comma divided tags

---

internal/git/repository.go
internal/lefthook/run/runner.go

Closes https://github.com/evilmartians/lefthook/issues/627
Relates to https://github.com/evilmartians/lefthook/issues/542
Check patch file size before trying to apply it. Remove the patch if it's empty and skip applying it.

fix: try ignoring empty patch files on pre commit hook

---

docs/configuration.md
internal/config/command.go
internal/config/script.go
internal/lefthook/run/runner.go
internal/lefthook/run/runner_test.go

Closes https://github.com/evilmartians/lefthook/discussions/683
This PR adds priorities to scripts.

feat: add priorities to scripts

---

internal/git/repository.go

Closes https://github.com/evilmartians/lefthook/issues/568
Closes https://github.com/evilmartians/lefthook/issues/100
If there's no upstream set then `git branch --remotes` returns nothing. In this case we want to fallback to the empty tree SHA (which can be changed, so I decided not to hard-code it). This feels correct if we are pushing the first change. If not – then lefthook can't figure out what changes are already pushed, so applying the diff from the empty tree feels correct too.
Please, create an issue/discussion if you have troubles with this change.

fix: fallback to empty tree sha when no upstream set

---

internal/git/remote.go
internal/lefthook/install.go

Closes https://github.com/evilmartians/lefthook/issues/680
When `install` called with force flag like `lefthook install -f` – drop the folders containing remotes and re-download them.

fix: when forced install redownload remotes

---

internal/git/repository.go
internal/git/repository_test.go

I faced an error like below (with LEFTHOOK_VERBOSE=true) when I partially added a file by `git add -p` and then executed `git commit`:
```
...
│ [lefthook] cmd: [git status --short]
│ [lefthook] dir: /path/to/my/repo
│ [lefthook] err: <nil>
│ [lefthook] out: MM xxx.yaml
│ [lefthook] saving partially staged files
│ [lefthook] cmd: [git diff --binary --unified=0 --no-color --no-ext-diff --src-prefix=a/ --dst-prefix=b/ --patch --submodule=short --output .git/info/lefthook-unstaged.patch -- 2mMM xxx.yaml]
│ [lefthook] dir: /path/to/my/repo
│ [lefthook] err: <nil>
│ [lefthook] out:
│ [lefthook] cmd: [git stash create]
│ [lefthook] dir: /path/to/my/repo
│ [lefthook] err: <nil>
│ [lefthook] out: ...
│ [lefthook] cmd: [git stash store --quiet --message lefthook auto backup ...]
│ [lefthook] dir: …
```

fix: add `--porcelain` to `git status --short`

---

cmd/run.go
internal/lefthook/run.go

Closes https://github.com/evilmartians/lefthook/discussions/715

feat: add run no auto install flag

---

internal/lefthook/runner/exec/execute_unix.go

Closes https://github.com/evilmartians/lefthook/discussions/709
`tty.Open` does not work with interactive bash scripts. I am about to dig into this issue but changing this to `os.Open("/dev/tty")` since it fixes the issue.

fix: enable interactive scripts

---

internal/version/version.go
testdata/min_version.txt

Closes https://github.com/evilmartians/lefthook/issues/718
Now when lefthook version mismatches the following error will be printed:
```
Error: required lefthook version (1.6.13) is higher than current (1.6.11) at /Users/me/go/bin/lefthook
```

fix: verbose error on versions mismatch

---

go.mod

Closes https://github.com/evilmartians/lefthook/discussions/725
Keep the toolchain separate

chore: remove go patch version

---

docs/install.md
internal/templates/hook.tmpl

Building on top of [previous PR that added Swift support](https://github.com/evilmartians/lefthook/pull/556). 
The `csjones/lefthook-plugin` Swift project has recently [added mint package manager support](https://github.com/csjones/lefthook-plugin/pull/4). To advertise this functionality, I wanted to mention this new feature in the lefthook docs. 
For my edits in this PR, I used the [previous PR that added Swift support](https://github.com/evilmartians/lefthook/pull/556) as a reference. I have not tested `internal/templates/hook.tmpl`, if it's even possible to do so. 
Thanks!

feat: expand Swift integration with Mint support

---

.github/workflows/lint.yml
.golangci.yml

Upgrade golangci-lint to 1.59.0 and config syntax for it.

chore(golangci-lint): upgrade to 1.59.0

---

.goreleaser.yml
internal/config/command.go
internal/config/command_executor.go
internal/config/hook.go
internal/config/script.go
internal/config/skip_checker.go
internal/config/skip_checker_test.go
internal/git/command_executor.go
internal/git/repository_test.go
internal/lefthook/lefthook.go
internal/lefthook/run_test.go
internal/lefthook/runner/exec/execute_unix.go
internal/lefthook/runner/exec/execute_windows.go
internal/lefthook/runner/exec/executor.go
internal/lefthook/runner/runner.go
internal/lefthook/runner/runner_test.go
internal/system/null_reader.go
internal/system/null_reader_test.go
internal/system/system.go

Closes https://github.com/evilmartians/lefthook/issues/730
`exec.Executor` interface does not need duplicated `RawExecute`, this code is moved to `system` package.
Also refactored some naming.

chore: refactor commands interfaces

---

internal/templates/hook.tmpl

Avoid running git and uname commands in scripts until their output is actually needed.
I suggest reviewing without showing whitespace changes due to changes in indentation.

perf: delay git and uname commands in hook scripts until needed

---

.golangci.yml

Add some more useful linters. There are no new findings to address at the moment.

chore(golangci-lint): enable copyloopvar, intrange, and prealloc

---

internal/lefthook/install.go
internal/lefthook/run.go

Related to https://github.com/evilmartians/lefthook/issues/743

fix: fetch remotes only for non ghost hooks

---

internal/lefthook/install.go

Closes https://github.com/evilmartians/lefthook/issues/743
If the lefthook config hasn't change, no need to overwrite the hooks.

fix: skip overwriting hooks when fetching data from remotes

---

internal/config/load.go

While using lefthook I found out the error message being shown was incorrect.
Two negations have been put in the same sentence.
I wanted to help, so here you have it :D

chore: setting proper error message for missing lefthook file

---

internal/config/load.go
testdata/many_extends_levels.txt

Closes https://github.com/evilmartians/lefthook/issues/753

fix: allow multiple levels of extends

---

internal/templates/hook.tmpl

Fixes #766
After using `range` `.Extension` cant be accessed on the resulting string. Two places where missed where this leads to a problem. They were replaced in this PR.

Fixed the use of '.Extension' in hook.tmpl

---

internal/templates/hook.tmpl

Having issues after upgrading:
The application resides in a sub directory, but lefthook tires to execute the binary in the project root:
```
.git/hooks/pre-commit: 37: /home/$PROJECT/node_modules/lefthook-linux-x64/bin/lefthook: not found
```
I think it was a copy&paste error.  Feel free to just close this PR if it's bogus.

Fix missing sub directory

---

internal/templates/hook.tmpl

Closes https://github.com/evilmartians/lefthook/issues/773
Instead of relying on `lefthook` package use direct `lefthook-{os}-{arch}` since we know the OS and the Arch.

fix: use direct lefthook package

---

docs/usage.md

Add missing documentation for the LEFTHOOK_OUTPUT environment variable.

docs: add docs for LEFTHOOK_OUTPUT var

---

docs/configuration.md
internal/config/command.go
internal/lefthook/runner/filters/filters.go
testdata/exclude.txt

Closes https://github.com/evilmartians/lefthook/issues/717

feat: allow list of files in exclude option

---

internal/templates/hook.tmpl
packaging/npm/lefthook-darwin-arm64/package.json
packaging/npm/lefthook-darwin-x64/package.json
packaging/npm/lefthook-freebsd-arm64/package.json
packaging/npm/lefthook-freebsd-x64/package.json
packaging/npm/lefthook-linux-arm64/package.json
packaging/npm/lefthook-linux-x64/package.json
packaging/npm/lefthook-windows-arm64/package.json
packaging/npm/lefthook-windows-x64/package.json

Closes https://github.com/evilmartians/lefthook/issues/775
Looks like optional dependencies (os-arch packages) conflict with the original `lefthook`. This was the only significant change that probably broke the behavior of `npx lefthook`.

fix: rollback packaging changes

---

docs/configuration.md
internal/lefthook/runner/filters/filters.go
testdata/exclude.txt

Instead of just checking full filenames use globs. This may be less performant, but more convenient, especially when using `exclude` option together with `glob`

feat: use glob in exclude array

---

.github/workflows/test.yml
.goreleaser.yml
Makefile

This change must fix https://github.com/evilmartians/lefthook/issues/783

fix: pass static flag to linker

---

.github/workflows/release.yml
.github/workflows/test.yml
.goreleaser.yml
Makefile
packaging/pack.rb

Fixes https://github.com/evilmartians/lefthook/issues/783
Just 🤦

fix: typo CGO_ENABLED instead of GCO_ENABLED

---

internal/config/command_executor.go
internal/config/skip_checker_test.go
internal/git/command_executor.go
internal/git/repository_test.go
internal/lefthook/run_test.go
internal/lefthook/runner/runner.go
internal/lefthook/runner/runner_test.go
internal/system/system.go

Closes https://github.com/evilmartians/lefthook/issues/803

fix: log stderr in debug logs only

---

cmd/root.go
docs/configuration.md
docs/usage.md
internal/lefthook/lefthook.go
internal/lefthook/run.go
internal/lefthook/runner/exec/execute_unix.go
internal/lefthook/runner/exec/execute_windows.go
internal/log/log.go

Closes https://github.com/evilmartians/lefthook/issues/581
Closes https://github.com/evilmartians/lefthook/issues/582

fix: add better colors control

---

docs/configuration.md

I just fixed the typo in the configuration.md.

Fix typo for command names in configuration.md

---

cmd/dump.go
internal/config/config.go
internal/git/state.go
internal/lefthook/dump.go
testdata/dump.txt

Find better names for a few methods and change `if`s to `switch`

chore: enhance some code parts

---

internal/lefthook/runner/runner.go

I noticed that the `skip: true` configuration I added to `post-checkout` was running LFS code. I also noticed that setting the environment variable `LEFTHOOK=0` did not run any LFS code.
This PR moves `r.Hook.DoSkip` closer to the top of `RunAll`, basically running less code when asked to skip.
I didn't really know how to test this! `runner_test.go` doesn't seem to test any LFS behavior. I'm pretty new to Go, so I'm unlikely to be able to heavily modify tests.

Run LFS hooks after checking if hooks are skipped

---

internal/git/remote.go
internal/lefthook/install.go

Closes https://github.com/evilmartians/lefthook/issues/826

fix: force remote name origin when using remotes

---

docs/configuration.md
docs/install.md

Re #608 
As per #608 hide the remaining links to the currently disabled Wiki.

chore: hide remaining wiki links

---

docs/usage.md

Closes https://github.com/evilmartians/lefthook/issues/216
Add a note to uninstall the lefthook executable manually

docs: mention to uninstall npm package

---

README.md
docs/install.md

Update the docs with instructions for installing lefthook on Alpine linux and with Python's pip

docs: update docs with new packages

---

.github/workflows/release.yml
packaging/pack.rb

Homebrew and Winget repos can be updated in parallel. Still need `build` to finish just to make sure the program is buildable.
Publishing of packages also moved to parallel jobs.

ci: parallelize publishing

---

docs/configuration.md
go.mod
internal/config/load.go
internal/config/load_test.go

Closes https://github.com/evilmartians/lefthook/discussions/852
Support globs in `extends` option.
Probably need to change checksum check from the file checksum to a memory object checksum – https://github.com/evilmartians/lefthook/pull/854

feat: support globs in extends

---

internal/config/config.go
internal/lefthook/dump.go
internal/lefthook/install.go
internal/lefthook/install_test.go

Instead of calculating the hashsum only for `lefthook.yml`, calculate the hashsum for the whole loaded config. If something changes – reinstall the hooks.

fix: calculate hashsum of the full config

---

internal/git/repository.go
internal/lefthook/runner/prepare_command.go

Closes https://github.com/evilmartians/lefthook/issues/292
Execute `files` from within a configured root in case it contains a path to a script. This is a breaking change.

fix: execute files command within configured root

---

internal/git/repository.go
internal/lefthook/runner/prepare_command.go
internal/templates/hook.tmpl

https://github.com/evilmartians/lefthook/discussions/599
As-is, if lefthook is not found, it will auto-install the latest lefthook from npm. (npx auto-fetches by default)
This isn't great:
1. Security: npm isn't known for being the most secure platform, and if the package was the target of an attack, _all_ lefthook users with node installed would be affected, even those who don't use the lefthook npm package.
2. User friendliness: installing binaries on the user's computer without their permission isn't great, and one of those lefthook binaries (an .exe file) was flagged by an anti-malware package at my organization.
It seems that the intention was to just print a message when lefthook is not found (which I agree with) and it's possible that using npx's …

Don't auto-install lefthook if not found

---

examples/commitlint/lefthook.yml

Commitizen wasn't called properly in the given example, and it was causing issues trying to commit twice (I can't believe no one came across this issue) with errors such as:
`fatal: cannot lock ref 'HEAD': is at ee79e382ba5d071408d1093ab56895a9076c7a55 but expected 073a7db08b49ac494c9023c0f4db29d406a12741`
It turns out, it needed the `--hook` parameter as specified in [commitizen docs](https://github.com/commitizen/cz-cli?tab=readme-ov-file#optional-running-commitizen-on-git-commit).

fix: commitizen wasn't called properly

---

docs/configuration.md
internal/config/remote.go
internal/lefthook/install.go
internal/lefthook/install_test.go

First of all, thanks everyone for the great tool!
The `remote` feature of lefthook allows us at the place where I work to easily share configuration across our hundreds of repositories. Usually, our devs have some dozens of repositories cloned on their machines and work actively in one or two at a time. To ensure that they will have a reasonably recent config when going back to a repo after some time, we configure our remotes with `refetch: true`, but this has the side effect that every time they run lefthook on a currently active repository, either by commiting something or by hand to manually check the output of the QA tools, they trigger a fetch.
To make the experience smother, this PR introduces a new parameter `refetch_frequency` that allows a more fine grained control over the …

feat: add refetch_frequency parameter to settings

---

internal/git/repository.go

Closes https://github.com/evilmartians/lefthook/issues/871
Add a argument `--path-format=absolute` to make sure that all git paths are absolute (relative paths don't work for some reason)

fix: use absolute paths when cloning remotes

---

docs/configuration.md

Add a missing link to the already existing documentation for the `output` config option.

fix: Add `output` to list of config options

---

docs/configuration.md

I'm a new user of Leftook, and I've had problems using it with VSCode. I followed the same steps as I did for setting up Husky. It's working for me.

Add docs for fnm configuration

---

.lefthook.toml
cmd/run.go
internal/config/config.go
internal/lefthook/run.go
internal/lefthook/runner/runner.go
internal/lefthook/runner/runner_test.go

https://github.com/evilmartians/lefthook/discussions/821
Git LFS is an opt-in feature that lets people store large files outside a git repository, saving only pointers to them in the git repository itself.
Git does not use LFS by default. One must manually specify files and file patterns using the `.gitattributes` file.
I've found that LFS adds about 2.2 seconds when running lefthook in my employer's large git repo.
<details>
<summary>My small benchmark</summary>
```
❯ /usr/bin/time git lfs post-checkout e6f8d32b e6f8d32b 0
2.24 real         0.39 user         1.51 sys
❯ /usr/bin/time git lfs post-checkout e6f8d32b e6f8d32b 0
2.22 real         0.39 user         1.50 sys
❯ /usr/bin/time git lfs post-checkout e6f8d32b e6f8d32b 0
2.28 real         0.41 user         1.51 sys
❯ /usr/bin/time …
```

Option to fully disable LFS hooks

---

.github/workflows/release.yml

Add a step that uses cloudsmith-cli to upload deb/rpm/apk packages

ci: automate publishing to cloudsmith

---

docs/install.md

Fixed a typo in the documentation section for 'Scoop for Windows'.

fix(docs): correct typo in 'Scoop for Windows' section

---

internal/git/repository.go
internal/version/version.go

You might face some issues when you have git version lower than 2.31.0. Git started supporting option `--path-format=absolute` only in 2.31.0. That's why we add a warning.

chore: add minimum git version support warning

---

internal/config/config.go

A colleague mentioned to me that the our two-second delay came back. Upon investigation, I noticed that lefthook wasn't reading the config flag anymore.

fix: skip_lfs config option

---

internal/config/command.go
internal/config/script.go
testdata/dump.txt

Fixes https://github.com/evilmartians/lefthook/issues/893
Specify key name for use_stdin option (koanf)

fix: correctly parse config options

---

.github/workflows/release.yml
.goreleaser.yml
packaging/aur/PKGBUILD
packaging/pack.rb

Automate releases to AUR registry for Arch Linux

ci: automate aur package update

---

docs/configuration.md
docs/install.md
docs/mdbook/configuration/run.md
docs/usage.md

Closes https://github.com/evilmartians/lefthook/issues/800

docs: explain run details

---

.github/workflows/release.yml
.goreleaser.yml
packaging/aur/PKGBUILD
packaging/pack.rb

ci: fix aur build

---

docs/install.md
docs/mdbook/installation/arch.md

Closes https://github.com/evilmartians/lefthook/issues/906
Add a mention of a community-driven lefthook-bin AUR package.

docs: add community aur package mention

---

cmd/run.go
internal/lefthook/run.go
internal/lefthook/runner/run_jobs.go
internal/lefthook/runner/runner.go
testdata/cli_run_only.txt

Idea from discussion of https://github.com/evilmartians/lefthook/issues/846

feat: add ability to specify job names to run command

---

.goreleaser.yml

Add gzipped aarch64 Linux build to release artifacts

ci: release linux aarch64 gz too

---

cmd/run.go
internal/lefthook/run.go

Adds `lefthook run foo --jobs <TAB>` completion, like there currently exists for `--commands`.

feat: run --jobs completion

---

internal/config/load.go
internal/config/load_test.go

Support replacing `{cmd}` in Jobs when merging lefthook-local

fix: replace cmd in jobs

---

internal/lefthook/install.go

For correctly getting files from node_modules for jobs check roots from jobs.

fix: use roots from jobs for possible npm package location

---

internal/git/repository.go
internal/lefthook/runner/jobs/build_command.go
internal/lefthook/runner/runner_test.go
testdata/pre-commit_issue_919.txt

Closes https://github.com/evilmartians/lefthook/issues/919
For `pre-commit` we use `git diff --diff-filter=ACMR` and this avoids checking for deleted files. But sometimes user wants a pre-commit hook to run on any change to the files (even when deleting files). For that cases (when `{staged_files}` template is not used) we should not force skipping the command/job.

fix: avoid skipping pre commit when deleted files staged

---

docs/mdbook/SUMMARY.md
docs/mdbook/configuration/README.md
docs/mdbook/configuration/lefthook.md
internal/config/config.go
internal/config/load.go
internal/lefthook/install.go
internal/templates/hook.tmpl
internal/templates/templates.go
schema.json
testdata/lefthook_option.txt

Closes https://github.com/evilmartians/lefthook/issues/443
There are two scenarios when you want to specify the lefthook executable or lefthook command:
1. You want to make sure developers in your project use the same lefthook version as installed in your project dependencies (makes sense when installing lefthook via npm, Ruby gems, PyPi)
2. You use PnP loader and have your `package.json` with lefthook dependency in a subdir. Currently there's no way to correctly do `cd subdir; yarn run lefthook`. This option can help with this.
The other special case is: you want to use your own lefthook executable defined in `lefthook-local.yml` (for whatever reason).
So, examples:
**Some hard-coded binary**
```yml
lefthook: /usr/bin/lefthook
pre-commit:
jobs:
- run: echo …
```

feat: allow to define lefthook executable or command

---

.typos.toml
internal/lefthook/install.go

Closes https://github.com/evilmartians/lefthook/issues/443

fix: use lefthook option in ghost hook too

---

internal/lefthook/runner/run_jobs.go

Avoid name collisions with groups

fix: unique names for nested operations

---

docs/mdbook/configuration/glob.md
internal/config/command.go
internal/config/job.go
internal/config/load_test.go
internal/lefthook/runner/filters/filters.go
internal/lefthook/runner/filters/filters_test.go
internal/lefthook/runner/jobs/jobs.go
internal/lefthook/runner/run_jobs.go
internal/lefthook/runner/runner_test.go
schema.json
testdata/dump.txt
testdata/job_merging.txt
testdata/many_extends_levels.txt
testdata/remotes.txt

Closes https://github.com/evilmartians/lefthook/issues/888

feat: allow providing a list of globs

---

docs/mdbook/configuration/glob.md
docs/mdbook/configuration/root.md

I had assumed that glob patterns work like they do with the *nix `ls` command, or in tools like lint-staged. I can imagine people expecting it to behave the same.
It seems that `**` is interpreted as a single asterisk, ie meaning "1+ directories deep", rather than "0 or more directories deep".
Whilst there is a link to the Go glob library used, and that README mentions double asterisks, I was mainly left confused by it:
> Syntax is inspired by [standard wildcards](http://tldp.org/LDP/GNU-Linux-Tools-Summary/html/x11655.htm), except that ** is aka super-asterisk, that do not sensitive for separators.
I don't think this covers the difference I'm bringing up. I also don't know what is meant by "super-asterisk" here - I'd love to know!
More details, including an example are in the commit …

Document the unusual behaviour of ** in glob option

---

internal/gen/jsonschema.go
schema.json

In the current jsonschema, specifying `$schema` results in a warning as shown in the following image.
This is because `"additionalProperties": false` and there is no `$schema` in `properties`.
To resolve this, the `$schema` property was added.  
This approach has been observed in other projects as well, such as [@biomejs/biome](https://github.com/biomejs/biome/blob/738ad51d654af10d5dd4faf5e8f8bdef5db81f09/packages/%40biomejs/biome/configuration_schema.json#L7-L10).
```diff
"properties": {
+     "$schema": {
+       "type": "string"
+     },
},
```
I am not very familiar with Go, so I would appreciate any corrections or suggestions.

fix(jsonschema): add $schema property

---

internal/config/skip_checker_test.go
internal/git/command_executor.go
internal/git/remote.go
internal/git/repository_test.go
internal/lefthook/run_test.go
internal/lefthook/runner/runner_test.go
internal/system/system.go
schema.json

Closes https://github.com/evilmartians/lefthook/issues/959

fix: remote issue with worktrees

---

internal/config/skip_checker_test.go
internal/git/command_executor.go
internal/git/remote.go
internal/git/repository_test.go
internal/lefthook/run_test.go
internal/lefthook/runner/runner_test.go
internal/system/system.go
schema.json

Closes https://github.com/evilmartians/lefthook/issues/962

fix: worktrees remote issue

---

internal/git/repository.go

Closes https://github.com/evilmartians/lefthook/issues/786
Unquote the file names in case git has `git core.quotepath true` setting.

fix: unquote paths to valid UTF-8

---

.github/workflows/gh-pages.yml

Freeze the mdbook version to 0.4.47 (in 0.4.48 duplicate file references are prohibited)

docs: allow duplicate files in SUMMARY

---

internal/lefthook/runner/exec/execute_windows.go

Issue # (989)
- changed:   internal/lefthook/runner/exec/execute_windows.go
- fix: fullPathSh: change `C:\Program Files\git\bin\sh.exe` to `sh.exe` for git bash installed in other directories
- fix: execute: cmdStr is dont escpape filename double quote, so replace these to escaped double quote

fix: fix command execution error on Windows #989

---

docs/mdbook/usage/env.md
docs/mdbook/usage/tips.md
packaging/npm-bundled/postinstall.js
packaging/npm-installer/install.js
packaging/npm/lefthook/postinstall.js

Allows installing hooks in CI (if it sets `CI=true` automatically) by setting `LEFTHOOK=1` or `LEFTHOOK=true` (recommended), or overriding it with `CI=0` or `CI=false`.
_Background_: MDN recently migrated most of its repositories from husky+lint-staged to lefthook, but we noticed that lefthook behaves different in CI (GitHub workflows): Husky installs hooks by default (which can be disabled with `HUSKY=0`), whereas lefthook doesn't install hooks (if `CI=true` is set). The only workarounds seem to have been setting `CI=""` (which may have side-effects on linting tools), or by running the hooks manually (e.g. via `npx lefthook run pre-commit`).

feat(npm): allow installing hooks in CI

---

docs/mdbook/installation/python.md
internal/templates/hook.tmpl

Document and support installing `lefthook` in a venv managed by `uv`.
Given the venv isn't activated, `lefthook` won't be in PATH, and we need to check for it the same way as with other package managers.

add support for uv

---

docs/mdbook/installation/mise.md
internal/templates/hook.tmpl

Add support for mise tool and a documentation on how to install lefthook using mise
Before the change Visual Code didn't run lefthook in the context of mise so it fails (it did work from the terminal though)

feat: add support for mise

---

README.md

Fixed a grammatical error in the Local config section of the `README.md`. Specifically, I have added the missing word “are” in "If you a frontend/backend developer" and replaced "into Docker" with "in Docker" for clarity.

docs: fix grammatical error in `Local config` section

---

docs/mdbook/configuration/README.md
internal/lefthook/run.go

[^1]: They still have to be within subdirs by hook name, e.g.: `.config/lefthook/pre-commit/lint.sh`

fix: load scripts from dot config too

---

docs/mdbook/installation/devbox.md
internal/templates/hook.tmpl

Add support for [Devbox tool](https://github.com/jetify-com/devbox) and a documentation on how to install lefthook using devbox
Before the change Visual Code didn't run lefthook in the context of devbox so it fails (it did work from the terminal though)

feat: add support for devbox

---

docs/mdbook/configuration/group.md
internal/lefthook/runner/run_jobs.go
testdata/group_envs.txt

Closes https://github.com/evilmartians/lefthook/issues/1053
Inherit `env` from a job where group is defined.
```yml
hook:
jobs:
- env:
E1: 1
E2: 2
group:
jobs:
- run: echo E1 - $E1
- run: echo E2 - $E2
- env:
E1: new
run: echo new E1 - $E1
```

feat: inherit group envs

---

cmd/run.go
internal/lefthook/run.go
internal/lefthook/runner/run_jobs.go
internal/lefthook/runner/runner.go
testdata/exclude_arg.txt

Closes https://github.com/evilmartians/lefthook/issues/593
Add ability to extend the exclude list manually via `--exclude` argument.
```
lefthook run pre-commit --exclude file1 --exclude file2
```
Works for jobs which don’t have `exclude: "regexp»` but instead use the glob list. If regexp is given it overwrites any inherited exclude list. Regexp excludes will be deprecated.
```yml
exclude:
- "glob1"
- "glob2"
```

feat: add exclude arg

---

docs/mdbook/configuration/files-global.md
docs/mdbook/configuration/files.md
docs/mdbook/configuration/run.md

I cleaned up the wording of the first line of the `run`, `files`, and `files-global` config entry descriptions a little bit, and added the information that the `sh` shell is used.
I removed the word "git" since my understanding is that there is no requirement that the provided command be a git command.

Improve wording of `run`, `files`, and `files-global` config descriptions, document that the `sh` shell is used

---

docs/mdbook/installation/node.md

There is a way not to turn off `side-effects-cache` completely, so I provided updated guidelines

docs: update pnpm installation note

---

internal/git/repository.go
tests/integrity/fail_on_changes.txt
tests/integrity/fail_on_changes_issue_1125.txt

Closes https://github.com/evilmartians/lefthook/issues/1125
Closes https://github.com/evilmartians/lefthook/pull/1128
Status is not being re-evaluated when calling `Changeset()`, it was using the cached results.
For `Changeset()` re-evaluate `git status --short`

fix: re evaluate status for changeset

---

cmd/run.go
internal/command/run.go
internal/run/controller/controller.go
internal/run/controller/job.go
tests/integrity/stage_fixed.txt

Closes https://github.com/evilmartians/lefthook/pull/1112
Sometimes you need to avoid auto staging changes even if there's a config option (valid for `pre-commit` hook only)
- Add `--no-stage-fixed` argument
- Avoid staging if `--no-stage-fixed` passed
- Avoid also stashing unstaged changes if `--no-stage-fixed` passed

feat: add no stage fixed argument

---

docs/mdbook/usage/env.md

The `LEFTHOOK_BIN` environment variable exists and has documentation in `docs/mdbook/usage/envs/LEFTHOOK_BIN.md`, but it's not included in the main environment variables documentation page at https://lefthook.dev/usage/env.html. This means users can't discover this useful environment variable through the documentation website.
I added this back in https://github.com/evilmartians/lefthook/pull/653
This PR adds the missing `LEFTHOOK_BIN` documentation to the main environment variables page by:
1. **Including the documentation**: Added `{{#include ./envs/LEFTHOOK_BIN.md}}` to `docs/mdbook/usage/env.md`
2. **Adding navigation entry**: Added `LEFTHOOK_BIN` to the navigation in `docs/mdbook/SUMMARY.md`
The `LEFTHOOK_BIN` environment variable allows users to specify a custom path to the lefthook …

docs: add LEFTHOOK_BIN environment variable to documentation

---

internal/log/log.go
internal/log/log_test.go

This PR adds comprehensive test coverage for the `SetName` and `UnsetName` methods in the log package, which are responsible for formatting the spinner suffix that displays hook names during execution.
While investigating [GitHub issue #1144](https://github.com/evilmartians/lefthook/issues/1144) (terminal width handling for spinner), we discovered that there were no tests covering the spinner formatting logic. This PR adds that missing test coverage and fixes a discovered bug.
- **`TestLogger_SetName`** (8 test cases): Basic functionality, edge cases, unicode support
- **`TestLogger_UnsetName`** (10 test cases): Removal scenarios, empty lists, duplicates
- **`TestLogger_SetName_UnsetName_Integration`**: Full workflow testing
- **`TestLogger_LongHookNames`**: Documents current …

Add comprehensive tests for spinner name formatting
