evilmartians/lefthook

.npm/README.md
README.md
context/context.go

Fix readme 
Remove git check in the command line

Fix readme & Remove git check in the command line

---

.npm/postinstall.js

Add CI check & prettify file

---

docs/node.md

I've added a link to the npm page, I tend to have a look at that page to have a look at stats (like usage & last publish), probably other people will search for it too.

Link to npm

---

.npm/postinstall.js

Another try @Arkweid 
I've added cwd argument to spawn, so it should work as earlier.

Fixed path to binaries

---

cmd/uninstall.go

All the context details about the improvement is on #96

remove only hooks and keep config files present Arkweid/lefthook#96

---

.travis.yml
CONTRIBUTING.md
cmd/add.go
cmd/install.go
cmd/templates.go
cmd/templates/config.tmpl
cmd/templates/hook.tmpl
cmd/uninstall.go
go.mod
spec/fixtures/pre-commit

- templates extracted
- golang version increased to support `//go:embed`
- autoinstall and run commands are using the same lookup function now

Extract templates

---

cmd/root.go

Support git workspaces and submodules

---

cmd/run.go
cmd/run_test.go

Case-insensitive glob

---

cmd/templates/config.tmpl
docs/full_guide.md
docs/node.md

Added small updates to docs
Moved the npm global installation example down.
Added tsx and jsx extensions

Docs micro-update

---

.npm/package.json

* Update package.json about project URLs

---

cmd/templates/hook.tmpl

Doc fixed in https://github.com/evilmartians/lefthook/pull/218
Template partially fixed in https://github.com/evilmartians/lefthook/pull/224

! Fix incorrect npx command in git hook script template

---

docs/full_guide.md

Fix typo in docs/full_guide.md

---

.gitignore
docs/node.md
internal/templates/hook.tmpl
packaging/npm/Makefile
packaging/npm/lefthook-darwin-arm64/package.json
packaging/npm/lefthook-darwin-x64/package.json
packaging/npm/lefthook-linux-arm64/package.json
packaging/npm/lefthook-linux-x64/package.json
packaging/npm/lefthook-windows-arm64/package.json
packaging/npm/lefthook-windows-x64/package.json
packaging/npm/lefthook/get-exe.js
packaging/npm/lefthook/package.json

Split npm package by os and cpu

---

docs/node.md

Now there are at least 3 ways to install.

fix: update node.md

---

docs/full_guide.md

Installation section in `full_guide.md` is outdated. To avoid duplications replacing it with links

docs: update full_guide.md

---

packaging/rubygems/lefthook.gemspec

Awkward bit of language in the gemspec message..

Fixing typo in gemspec

---

cmd/uninstall.go
internal/lefthook/uninstall.go
internal/lefthook/uninstall_test.go

Closes https://github.com/evilmartians/lefthook/issues/325
**Summary changes to `uninstall` command :wrench:**

Dont remove config by default

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md

Moving some issues to Discussions in order to keep things in right places and better control them.

New issue template

---

docs/usage.md
internal/lefthook/run.go

Closes https://github.com/evilmartians/lefthook/issues/344

feature: Add LEFTHOOK_VERBOSE env

---

cmd/uninstall.go
internal/config/command.go
internal/config/hook.go
internal/config/load.go
internal/config/load_test.go
internal/config/script.go
internal/lefthook/lefthook.go

chore: Remove deprecated config options

---

internal/lefthook/run.go

Closes https://github.com/evilmartians/lefthook/discussions/355
Print `prepare-commit-msg` hook execution if it exists in config

fix: Print prepare-commit-msg hook if it exists in config

---

CHANGELOG.md
packaging/Makefile
packaging/npm/lefthook-freebsd-arm64/package.json
packaging/npm/lefthook-freebsd-x64/package.json
packaging/npm/lefthook/package.json
packaging/rubygems/bin/lefthook

chore: Add FreeBSD OS to packages

---

.github/dependabot.yml
.github/workflows/codeql.yml

- Add code analyzing GitHub action

chore: Add codeql github action

---

internal/templates/hook.tmpl

Closes https://github.com/evilmartians/lefthook/issues/250

feature: Use pnpm before npx

---

cmd/run.go
docs/configuration.md
internal/config/hook.go
internal/lefthook/run.go
internal/lefthook/runner/execute_unix.go
internal/lefthook/runner/execute_windows.go
internal/lefthook/runner/executor.go
internal/lefthook/runner/runner.go
internal/lefthook/runner/runner_test.go

Closes https://github.com/evilmartians/lefthook/issues/208

feature: Allow following output

---

go.mod
go.sum

- https://github.com/evilmartians/lefthook/pull/406

Dependencies

---

CONTRIBUTING.md
docs/configuration.md

Doc updates only.
- [ X] Check locally
- [ X] Add tests

docs: Fix typos in docs/configuration.md and CONTRIBUTING.md.

---

go.mod
go.sum

- https://github.com/evilmartians/lefthook/pull/486

Dependencies 05.2023

---

.github/workflows/test.yml
CHANGELOG.md
CONTRIBUTING.md
Makefile
README.md
cmd/dump.go
go.mod
internal/config/command.go
internal/config/config.go
internal/config/hook.go
internal/config/load_test.go
internal/config/remote.go
internal/config/script.go
internal/lefthook/dump.go
internal/lefthook/install.go

Add toml dumping

---

.github/workflows/test.yml
cmd/lefthook.go
go.mod
go.sum
integrity_test.go
main.go
testdata/add.txt
testdata/dump.txt
testdata/install.txt
testdata/version.txt

This PR adds tests that check lefthook binary integrity

chore: add integrity tests

---

.github/workflows/test.yml
testdata/dump.txt
testdata/hide_unstaged.txt
testdata/min_version.txt
testdata/remote.txt
testdata/run_script.txt
testdata/run_toml.txt
testdata/stage_fixed.txt
testdata/version.txt

Add more tests to cover git-specific business logic

chore: add extra integrity tests

---

go.mod
go.sum

- https://github.com/evilmartians/lefthook/pull/513
- https://github.com/evilmartians/lefthook/pull/522

Dependencies 18 July, 2023

---

.github/PULL_REQUEST_TEMPLATE.md

I'm weary of adding too many steps to these in case so they aren't ignored, but this is something I've been asked to do in a few PRs.
May as well add it to the checklist!

Add docs to PR template

---

docs/configuration.md
internal/config/config.go
internal/lefthook/add.go
internal/lefthook/install.go
internal/lefthook/lefthook.go
internal/templates/hook.tmpl
internal/templates/templates.go

feat: add assert_lefthook_installed option

---

internal/git/repository.go

Closes https://github.com/evilmartians/lefthook/issues/612
Remove space in the arguments list

fix: pre push hook handling

---

cmd/add.go
cmd/dump.go
cmd/install.go
cmd/uninstall.go
cmd/version.go

Fix and add command argument count validation.

fix: command argument count validations

---

.github/workflows/codeql.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/test.yml

Update versions of Github actions

ci: update github actions versions

---

.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/test.yml
CONTRIBUTING.md
README.md
go.mod

chore: bump go to 1.22

---

Makefile
docs/configuration.md
go.mod
internal/config/remote.go
internal/git/remote.go
internal/lefthook/install.go
internal/lefthook/run.go

Closes https://github.com/evilmartians/lefthook/issues/736
- Add `refetch` option to remotes that makes sure remotes are refetched on every call
- Add a spinner telling that it's fetching the remotes

feat: add refetch option to remotes config

---

internal/config/load.go
internal/config/load_test.go

Closes https://github.com/evilmartians/lefthook/issues/753

fix: apply local extends only if they are present

---

.github/workflows/test.yml

ci: retriable integrity tests

---

docs/install.md

Closes https://github.com/evilmartians/lefthook/issues/760
Add a note about .npmrc and pnpm package to enable postinstall script for lefthook

docs: add a note about pnpm

---

internal/templates/hook.tmpl
packaging/npm-bundled/get-exe.js
packaging/npm-bundled/package.json
packaging/npm-installer/install.js
packaging/npm-installer/package.json
packaging/pack.rb
packaging/rubygems/bin/lefthook

Fix publishing scripts + use direct OS+Arch versions when possible

fix: publishing

---

internal/lefthook/runner/filters/filters.go
testdata/exclude.txt

Closes https://github.com/evilmartians/lefthook/issues/781

fix: multiple excludes

---

.github/workflows/release.yml
.github/workflows/test.yml

ci: use latest goreleaser

---

.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/test.yml
internal/git/command_executor.go
internal/lefthook/runner/runner.go

ci: update workflow files

---

packaging/npm-bundled/package.json
packaging/npm-installer/package.json
packaging/npm/lefthook-darwin-arm64/package.json
packaging/npm/lefthook-darwin-x64/package.json
packaging/npm/lefthook-freebsd-arm64/package.json
packaging/npm/lefthook-freebsd-x64/package.json
packaging/npm/lefthook-linux-arm64/package.json
packaging/npm/lefthook-linux-x64/package.json
packaging/npm/lefthook-windows-arm64/package.json
packaging/npm/lefthook-windows-x64/package.json
packaging/npm/lefthook/package.json

fix: npm fix packages

---

packaging/npm/lefthook-darwin-arm64/package.json
packaging/npm/lefthook-darwin-x64/package.json
packaging/npm/lefthook-freebsd-arm64/package.json
packaging/npm/lefthook-freebsd-x64/package.json
packaging/npm/lefthook-linux-arm64/package.json
packaging/npm/lefthook-linux-x64/package.json
packaging/npm/lefthook-windows-arm64/package.json
packaging/npm/lefthook-windows-x64/package.json
packaging/npm/lefthook/package.json

Another try for https://github.com/evilmartians/lefthook/pull/776

packaging: try direct lefthook executable for npm

---

packaging/npm/lefthook-darwin-arm64/package.json
packaging/npm/lefthook-darwin-x64/package.json
packaging/npm/lefthook-freebsd-arm64/package.json
packaging/npm/lefthook-freebsd-x64/package.json
packaging/npm/lefthook-linux-arm64/package.json
packaging/npm/lefthook-linux-x64/package.json
packaging/npm/lefthook-windows-arm64/package.json
packaging/npm/lefthook-windows-x64/package.json
packaging/npm/lefthook/package.json

Revert https://github.com/evilmartians/lefthook/pull/794

fix: revert packaging change

---

README.md
docs/configuration.md
docs/usage.md

Slightly simplify and actualize the docs.

docs: actualize docs

---

docs/configuration.md

Closes https://github.com/evilmartians/lefthook/issues/837
Update the docs, so the order of merging configs is documented.

docs: update info about merge order

---

.goreleaser.yml

Closes https://github.com/evilmartians/lefthook/issues/502
In this PR we only generate the package. Future plan is to add lefthook to Alpine registry

ci: generate apk files

---

.github/workflows/release.yml
.gitignore
packaging/pack.rb
packaging/pypi/LICENSE
packaging/pypi/README.md
packaging/pypi/lefthook/__main__.py
packaging/pypi/lefthook/main.py
packaging/pypi/setup.py

Closes https://github.com/evilmartians/lefthook/issues/119

feat: add python package

---

internal/updater/updater.go

Downloading 10Mb may take some time if you have a slow connection

fix: increase self update download timeout

---

go.mod
go.sum

- [deps: bump github.com/schollz/progressbar/v3 from 3.16.0 to 3.17.0](https://github.com/evilmartians/lefthook/commit/005cdcfcf47ae3e78a343560a498c3dc473a76d4)
- [deps: bump github.com/creack/pty from 1.1.23 to 1.1.24](https://github.com/evilmartians/lefthook/commit/c9229f952c0e822a97ec908da397595b13f2d97b)
- [deps: bump github.com/charmbracelet/lipgloss from 0.13.0 to 0.13.1](https://github.com/evilmartians/lefthook/commit/ee48f0197d9010b15b13c6b495fb362149fd9b58)
- [deps: bump github.com/charmbracelet/lipgloss from 0.13.1 to 1.0.0](https://github.com/evilmartians/lefthook/commit/21a832bea8725d96298515a75b023b2f824aead4)

deps: November 2024

---

.github/workflows/release.yml

ci: fix packages release

---

README.md
docs/mdbook/configuration/output.md
docs/mdbook/configuration/skip_output.md

- Update links to use gh-pages

docs: update readme to use mdbook

---

docs/mdbook/configuration/jobs.md
internal/lefthook/runner/run_jobs.go
testdata/exclude.txt

Closes https://github.com/evilmartians/lefthook/issues/912

feat: inherit exclude option in groups

---

cmd/uninstall.go

docs: make uninstall --remote-configs description more accurate

---

docs/mdbook/configuration/templates.md

Changed example to specify override in `lefthook-local.yml`

docs: Fix templates override example lefthook-local.yml

---

internal/git/command_executor.go
internal/lefthook/runner/filters/filters.go
internal/lefthook/runner/jobs/build_command.go
internal/log/builder.go
internal/log/log.go
internal/system/system.go

chore: fancier logging

---

internal/git/command_executor.go
internal/lefthook/runner/filters/filters.go
internal/lefthook/runner/jobs/build_command.go
internal/lefthook/runner/runner.go
internal/log/builder.go
internal/log/log.go
internal/system/system.go
testdata/remote.txt
testdata/remotes.txt

Closes https://github.com/evilmartians/lefthook/issues/685
If Git command returned non-0, log the error

fix: print git errors 

---

.github/workflows/release.yml
packaging/aur/lefthook-bin/PKGBUILD
packaging/pack.rb

packaging: aur fixes

---

internal/lefthook/runner/exec/execute_windows.go

Closes https://github.com/evilmartians/lefthook/issues/989
1. Check if `C:\Program Files\Git\bin\sh.exe` exists
2. Then check if we can access `sh` from the PATH
3. Then check the `git` base and use `../bin/sh.exe`
This should cover even more cases of Git installation on Windows.
This PR brings small improvements to https://github.com/evilmartians/lefthook/pull/992 PR

fix: windows sh lookup

---

.lefthook.yml
internal/config/command_executor.go
internal/config/skip_checker.go
internal/git/command_executor.go
internal/git/repository.go
internal/lefthook/runner/filters/filters.go
internal/lefthook/runner/jobs/build_command.go
internal/lefthook/runner/jobs/jobs.go
internal/lefthook/runner/runner.go
internal/log/builder.go
internal/system/system.go

Closes https://github.com/evilmartians/lefthook/issues/1002

fix: better logging

---

internal/lefthook/run.go

Make `lefthook run foo --jobs <TAB>` complete all jobs, recursively in nested groups too.
This isn't terribly efficient, but should do the job.

feat(run): complete all job names, recursively

---

.github/workflows/lint.yml
.golangci.yml
Makefile
internal/config/command.go
internal/config/config.go
internal/config/files.go
internal/git/state.go
internal/lefthook/add.go
internal/lefthook/install.go
internal/lefthook/lefthook.go
internal/lefthook/run.go
internal/lefthook/runner/exec/execute_unix.go
internal/lefthook/runner/filters/filters.go
internal/lefthook/runner/result.go
internal/lefthook/runner/runner.go
internal/lefthook/uninstall.go
internal/lefthook/validate.go
internal/updater/updater.go
internal/updater/updater_test.go

Upgrade golangci-lint to v2, update config for it, address findings.
See individual commits for details.

chore: upgrade golangci-lint to v2, address findings

---

internal/config/load.go
internal/git/repository.go
internal/git/state.go
internal/lefthook/install.go
internal/lefthook/lefthook.go
internal/version/version.go

Some small improvements to regexp use.

Regexp use improvements

---

internal/lefthook/run.go
internal/lefthook/runner/result.go
internal/lefthook/runner/result/result.go
internal/lefthook/runner/run_jobs.go
internal/lefthook/runner/runner.go
internal/lefthook/runner/runner_test.go
internal/log/log.go

Closes https://github.com/evilmartians/lefthook/pull/1030
This PR adds tests to https://github.com/evilmartians/lefthook/pull/1030

feat: show time for steps

---

cmd/install.go
docs/mdbook/usage/commands.md
internal/command/install.go
internal/command/install_test.go
internal/command/uninstall.go
internal/templates/templates.go
testdata/install_specific.txt

Closes https://github.com/evilmartians/lefthook/pull/1059
Closes https://github.com/evilmartians/lefthook/issues/1058
`lefthook install pre-commit` installs and then syncs only the specified `pre-commit` hook.
**Note**: `lefthook install` will reinstall all hooks

feat: allow installing only specific hooks

---

internal/config/job.go
internal/run/controller/job.go
internal/run/controller/scope.go
internal/run/controller/scope_test.go
schema.json
tests/helpers/configtest/config.go
tests/helpers/configtest/config_test.go

Closes https://github.com/evilmartians/lefthook/issues/1134
`file_types` can also be inherited from a group job
- Added `file_types` to the inherited scope

feat: inherit file_types from parent jobs

---

.github/workflows/test.yml
cmd/validate.go
integration_test.go
internal/command/validate.go
internal/config/hook.go
internal/config/script.go
tests/integration/check_install.txt
tests/integration/validate.txt
tests/integration/validate_fail.txt

chore: tests improvements
